import { createClient } from 'npm:@supabase/supabase-js@2';
const url=Deno.env.get('SUPABASE_URL')!, secret=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, anon=Deno.env.get('SUPABASE_ANON_KEY')!, origin=Deno.env.get('PAINEL_ORIGIN')||'https://viniciusnevesdev.github.io', home=Deno.env.get('PAINEL_URL')||'https://viniciusnevesdev.github.io/Painel/';
const admin=createClient(url,secret,{auth:{persistSession:false}});const headers={'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json'};
const reply=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers});
const blank={lists:[{id:'default',title:'Geral'}],tasks:[],notes:[]};
async function checked(p:any){const {error}=await p;if(error)throw Error('Falha ao acessar o banco. Confira a configuração.');}
function validState(s:any){if(!s||!Array.isArray(s.lists)||!s.lists.length||!Array.isArray(s.tasks)||!Array.isArray(s.notes))return false;for(const arr of [s.lists,s.tasks,s.notes]){if(arr.length>5000||new Set(arr.map((x:any)=>x.id)).size!==arr.length)return false;for(const x of arr)if(typeof x.id!=='string'||typeof x.title!=='string'||x.title.length>200)return false}for(const n of s.notes){if(!['none','daily','weekly'].includes(n.repeat)||!Array.isArray(n.days)||!Array.isArray(n.times)||n.times.length>48||n.days.some((d:any)=>!Number.isInteger(d)||d<0||d>6)||n.times.some((t:any)=>!/^([01]\d|2[0-3]):[0-5]\d$/.test(t)))return false;for(const key of ['starts','ends','hiddenUntil','resurfaceAt','deletedAt'])if(n[key]&&!Number.isFinite(Date.parse(n[key])))return false}for(const t of s.tasks){if(t.dueDate&&!/^\d{4}-\d{2}-\d{2}$/.test(t.dueDate))return false;if(t.dueTime&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(t.dueTime))return false;if(!Array.isArray(t.before)||t.before.some((v:any)=>!Number.isInteger(v)||v<0||v>525600))return false}return true}
async function googleToken(refresh:string){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({client_id:Deno.env.get('GOOGLE_CLIENT_ID')!,client_secret:Deno.env.get('GOOGLE_CLIENT_SECRET')!,refresh_token:refresh,grant_type:'refresh_token'})});const d=await r.json();if(!r.ok)throw Error('Reconecte a conta Google em Ajustes.');return d.access_token}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{headers});const requestUrl=new URL(req.url);if(req.method==='GET'&&requestUrl.searchParams.has('state')){let ok=false;try{const token=requestUrl.searchParams.get('state')!;const {data,error}=await admin.from('painel_oauth').delete().eq('token',token).gt('expires_at',new Date().toISOString()).select().single();if(error||!data||!requestUrl.searchParams.get('code'))throw Error('Invalid state');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({code:requestUrl.searchParams.get('code')!,client_id:Deno.env.get('GOOGLE_CLIENT_ID')!,client_secret:Deno.env.get('GOOGLE_CLIENT_SECRET')!,redirect_uri:`${url}/functions/v1/api`,grant_type:'authorization_code'})});const g=await r.json();if(!r.ok||!g.refresh_token)throw Error('No refresh token');const info=await fetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:{Authorization:`Bearer ${g.access_token}`}}).then(r=>r.json());if(!info.email)throw Error('No email');await checked(admin.from('painel_google').upsert({user_id:data.user_id,email:info.email,refresh_token:g.refresh_token},{onConflict:'user_id,email'}));ok=true}catch{console.error('Google authorization failed')}return Response.redirect(home+'?google='+(ok?'ok':'error'),303)}
try{if(req.method!=='POST')return reply({error:'Método inválido.'},405);if(Number(req.headers.get('content-length'))>3000000)return reply({error:'Conteúdo muito grande.'},413);const text=await req.text();if(text.length>3000000)return reply({error:'Conteúdo muito grande.'},413);const body=JSON.parse(text);if(body.action==='config')return reply({key:anon});const bearer=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!bearer)return reply({error:'Faça login.'},401);const {data:{user},error}=await admin.auth.getUser(bearer);if(error||!user)return reply({error:'Sua sessão expirou. Entre novamente.'},401);const uid=user.id;
switch(body.action){case 'read':{const {data,error}=await admin.from('painel_state').select('revision,state').eq('user_id',uid).maybeSingle();if(error)throw Error('Banco não configurado.');return reply(data||{revision:0,state:blank})}
case 'save':{if(!validState(body.state)||!Number.isSafeInteger(body.revision))return reply({error:'Dados inválidos.'},400);const {data,error}=await admin.rpc('painel_save',{p_user:uid,p_revision:body.revision,p_state:body.state});if(error)return reply({error:error.message.includes('CONFLICT')?'Conflito: sincronize antes de salvar.':'Não foi possível salvar.'},409);return reply({revision:data})}
case 'google-start':{if(!Deno.env.get('GOOGLE_CLIENT_ID')||!Deno.env.get('GOOGLE_CLIENT_SECRET'))return reply({error:'Google Agenda ainda não configurado no backend.'},503);const token=crypto.randomUUID();await checked(admin.from('painel_oauth').insert({token,user_id:uid,expires_at:new Date(Date.now()+600000).toISOString()}));const auth=new URL('https://accounts.google.com/o/oauth2/v2/auth');auth.search=new URLSearchParams({client_id:Deno.env.get('GOOGLE_CLIENT_ID')!,redirect_uri:`${url}/functions/v1/api`,response_type:'code',scope:'openid email https://www.googleapis.com/auth/calendar.events.readonly',access_type:'offline',prompt:'consent select_account',state:token}).toString();return reply({url:auth.toString()})}
case 'calendar':{const {data,error}=await admin.from('painel_google').select('*').eq('user_id',uid);if(error)throw Error('Banco não configurado.');const events:any[]=[];for(const account of data||[]){const token=await googleToken(account.refresh_token);const now=new Date();const start=new Date(now.getTime()-86400000).toISOString();const end=new Date(now.getTime()+30*86400000).toISOString();let page='';do{const q=new URLSearchParams({timeMin:start,timeMax:end,singleEvents:'true',orderBy:'startTime',maxResults:'250',...(page?{pageToken:page}:{})});const r=await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events?'+q,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw Error('Não foi possível consultar o Google Agenda.');events.push(...(d.items||[]).filter((e:any)=>e.status!=='cancelled').map((e:any)=>({id:e.id,summary:e.summary,start:e.start,end:e.end,location:e.location,account:account.email})));page=d.nextPageToken||''}while(page)}return reply({accounts:(data||[]).map(a=>({email:a.email})),events})}
case 'push-config':return reply({key:Deno.env.get('VAPID_PUBLIC_KEY')||null});
case 'subscribe':{const s=body.subscription;if(!s?.endpoint?.startsWith('https://')||!s.keys?.p256dh||!s.keys?.auth)return reply({error:'Inscrição inválida.'},400);const host=new URL(s.endpoint).hostname;if(!host.endsWith('.push.apple.com')&&host!=='fcm.googleapis.com'&&host!=='updates.push.services.mozilla.com')return reply({error:'Provedor de push não permitido.'},400);await checked(admin.from('painel_push').upsert({endpoint:s.endpoint,user_id:uid,subscription:s},{onConflict:'endpoint'}));return reply({ok:true})}
case 'unsubscribe':await checked(admin.from('painel_push').delete().eq('user_id',uid).eq('endpoint',body.endpoint||''));return reply({ok:true});
default:return reply({error:'Ação inválida.'},400)}}catch(e){console.error('API error',e.message);return reply({error:e.message||'Erro no servidor.'},500)}});
